--- a/.github/workflows/integration_tests_validation.yaml
+++ b/.github/workflows/integration_tests_validation.yaml
@@ -96,4 +96,4 @@
       - name: Build
         run: just runtimetest contest
       - name: Validate tests on runc
-        run: just validate-contest-runc
+        run: just validate-contest-runc